import type { Question } from './types';
import type { RoomSettings } from '@/features/room/types';

/**
 * Fetch questions for a game session.
 *
 * TODO: Replace this stub with a real DB / API call.
 * The function signature is stable — only the implementation needs to change.
 */
const QUESTION_BANK: Record<string, Question[]> = {
  general: [
    {
      id: 'q-gen-1',
      text: 'What is the largest planet in our solar system?',
      options: [
        { id: 'a', text: 'Jupiter' },
        { id: 'b', text: 'Saturn' },
        { id: 'c', text: 'Neptune' },
        { id: 'd', text: 'Earth' },
      ],
      correctOptionId: 'a',
      category: 'general',
    },
    {
      id: 'q-gen-2',
      text: 'Which element has the chemical symbol Fe?',
      options: [
        { id: 'a', text: 'Fluorine' },
        { id: 'b', text: 'Iron' },
        { id: 'c', text: 'Francium' },
        { id: 'd', text: 'Fermium' },
      ],
      correctOptionId: 'b',
      category: 'general',
    },
    {
      id: 'q-gen-3',
      text: 'Who painted the Mona Lisa?',
      options: [
        { id: 'a', text: 'Vincent van Gogh' },
        { id: 'b', text: 'Pablo Picasso' },
        { id: 'c', text: 'Leonardo da Vinci' },
        { id: 'd', text: 'Michelangelo' },
      ],
      correctOptionId: 'c',
      category: 'general',
    },
    {
      id: 'q-gen-4',
      text: 'What is the smallest country in the world by area?',
      options: [
        { id: 'a', text: 'Monaco' },
        { id: 'b', text: 'San Marino' },
        { id: 'c', text: 'Vatican City' },
        { id: 'd', text: 'Liechtenstein' },
      ],
      correctOptionId: 'c',
      category: 'general',
    },
    {
      id: 'q-gen-5',
      text: 'In which year did the Titanic sink?',
      options: [
        { id: 'a', text: '1905' },
        { id: 'b', text: '1912' },
        { id: 'c', text: '1918' },
        { id: 'd', text: '1923' },
      ],
      correctOptionId: 'b',
      category: 'general',
    },
    {
      id: 'q-gen-6',
      text: 'What is the hardest natural substance on Earth?',
      options: [
        { id: 'a', text: 'Gold' },
        { id: 'b', text: 'Iron' },
        { id: 'c', text: 'Diamond' },
        { id: 'd', text: 'Platinum' },
      ],
      correctOptionId: 'c',
      category: 'general',
    },
    {
      id: 'q-gen-7',
      text: 'Which country gifted the Statue of Liberty to the USA?',
      options: [
        { id: 'a', text: 'United Kingdom' },
        { id: 'b', text: 'Germany' },
        { id: 'c', text: 'Italy' },
        { id: 'd', text: 'France' },
      ],
      correctOptionId: 'd',
      category: 'general',
    },
    {
      id: 'q-gen-8',
      text: 'What is the currency of Japan?',
      options: [
        { id: 'a', text: 'Won' },
        { id: 'b', text: 'Yuan' },
        { id: 'c', text: 'Yen' },
        { id: 'd', text: 'Ringgit' },
      ],
      correctOptionId: 'c',
      category: 'general',
    },
    {
      id: 'q-gen-9',
      text: 'How many continents are there on Earth?',
      options: [
        { id: 'a', text: '5' },
        { id: 'b', text: '6' },
        { id: 'c', text: '7' },
        { id: 'd', text: '8' },
      ],
      correctOptionId: 'c',
      category: 'general',
    },
    {
      id: 'q-gen-10',
      text: 'What is the main ingredient in guacamole?',
      options: [
        { id: 'a', text: 'Tomato' },
        { id: 'b', text: 'Avocado' },
        { id: 'c', text: 'Pepper' },
        { id: 'd', text: 'Onion' },
      ],
      correctOptionId: 'b',
      category: 'general',
    },
  ],
  science: [
    {
      id: 'q-sci-1',
      text: 'What is the speed of light in a vacuum (approx)?',
      options: [
        { id: 'a', text: '150,000 km/s' },
        { id: 'b', text: '300,000 km/s' },
        { id: 'c', text: '500,000 km/s' },
        { id: 'd', text: '1,000,000 km/s' },
      ],
      correctOptionId: 'b',
      category: 'science',
    },
    {
      id: 'q-sci-2',
      text: 'Which gas do plants absorb from the atmosphere during photosynthesis?',
      options: [
        { id: 'a', text: 'Oxygen' },
        { id: 'b', text: 'Nitrogen' },
        { id: 'c', text: 'Carbon dioxide' },
        { id: 'd', text: 'Hydrogen' },
      ],
      correctOptionId: 'c',
      category: 'science',
    },
    {
      id: 'q-sci-3',
      text: 'What is the powerhouse of the cell?',
      options: [
        { id: 'a', text: 'Nucleus' },
        { id: 'b', text: 'Mitochondria' },
        { id: 'c', text: 'Ribosome' },
        { id: 'd', text: 'Golgi apparatus' },
      ],
      correctOptionId: 'b',
      category: 'science',
    },
    {
      id: 'q-sci-4',
      text: 'What is the chemical formula for water?',
      options: [
        { id: 'a', text: 'CO₂' },
        { id: 'b', text: 'H₂O' },
        { id: 'c', text: 'O₂' },
        { id: 'd', text: 'NaCl' },
      ],
      correctOptionId: 'b',
      category: 'science',
    },
    {
      id: 'q-sci-5',
      text: 'Which planet is known as the Red Planet?',
      options: [
        { id: 'a', text: 'Venus' },
        { id: 'b', text: 'Jupiter' },
        { id: 'c', text: 'Mars' },
        { id: 'd', text: 'Saturn' },
      ],
      correctOptionId: 'c',
      category: 'science',
    },
    {
      id: 'q-sci-6',
      text: 'What particle has a negative charge?',
      options: [
        { id: 'a', text: 'Proton' },
        { id: 'b', text: 'Neutron' },
        { id: 'c', text: 'Electron' },
        { id: 'd', text: 'Photon' },
      ],
      correctOptionId: 'c',
      category: 'science',
    },
    {
      id: 'q-sci-7',
      text: "What is the most abundant gas in Earth's atmosphere?",
      options: [
        { id: 'a', text: 'Oxygen' },
        { id: 'b', text: 'Carbon dioxide' },
        { id: 'c', text: 'Nitrogen' },
        { id: 'd', text: 'Argon' },
      ],
      correctOptionId: 'c',
      category: 'science',
    },
    {
      id: 'q-sci-8',
      text: 'Which organ is responsible for filtering blood in the human body?',
      options: [
        { id: 'a', text: 'Liver' },
        { id: 'b', text: 'Heart' },
        { id: 'c', text: 'Kidneys' },
        { id: 'd', text: 'Stomach' },
      ],
      correctOptionId: 'c',
      category: 'science',
    },
    {
      id: 'q-sci-9',
      text: 'What is the SI unit of electric current?',
      options: [
        { id: 'a', text: 'Volt' },
        { id: 'b', text: 'Watt' },
        { id: 'c', text: 'Ohm' },
        { id: 'd', text: 'Ampere' },
      ],
      correctOptionId: 'd',
      category: 'science',
    },
    {
      id: 'q-sci-10',
      text: 'Which vitamin is primarily produced when skin is exposed to sunlight?',
      options: [
        { id: 'a', text: 'Vitamin A' },
        { id: 'b', text: 'Vitamin B12' },
        { id: 'c', text: 'Vitamin C' },
        { id: 'd', text: 'Vitamin D' },
      ],
      correctOptionId: 'd',
      category: 'science',
    },
  ],
  history: [
    {
      id: 'q-his-1',
      text: 'In which year did World War II end?',
      options: [
        { id: 'a', text: '1943' },
        { id: 'b', text: '1944' },
        { id: 'c', text: '1945' },
        { id: 'd', text: '1946' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
    {
      id: 'q-his-2',
      text: 'Who was the first President of the United States?',
      options: [
        { id: 'a', text: 'Thomas Jefferson' },
        { id: 'b', text: 'Abraham Lincoln' },
        { id: 'c', text: 'George Washington' },
        { id: 'd', text: 'John Adams' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
    {
      id: 'q-his-3',
      text: 'The ancient city of Rome was built on how many hills?',
      options: [
        { id: 'a', text: 'Five' },
        { id: 'b', text: 'Seven' },
        { id: 'c', text: 'Nine' },
        { id: 'd', text: 'Twelve' },
      ],
      correctOptionId: 'b',
      category: 'history',
    },
    {
      id: 'q-his-4',
      text: 'Which empire was ruled by Genghis Khan?',
      options: [
        { id: 'a', text: 'Roman Empire' },
        { id: 'b', text: 'Ottoman Empire' },
        { id: 'c', text: 'Mongol Empire' },
        { id: 'd', text: 'British Empire' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
    {
      id: 'q-his-5',
      text: 'The Great Wall of China was primarily built during which dynasty?',
      options: [
        { id: 'a', text: 'Han' },
        { id: 'b', text: 'Tang' },
        { id: 'c', text: 'Ming' },
        { id: 'd', text: 'Qing' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
    {
      id: 'q-his-6',
      text: 'Who discovered penicillin?',
      options: [
        { id: 'a', text: 'Louis Pasteur' },
        { id: 'b', text: 'Marie Curie' },
        { id: 'c', text: 'Alexander Fleming' },
        { id: 'd', text: 'Joseph Lister' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
    {
      id: 'q-his-7',
      text: 'In which country did the Industrial Revolution begin?',
      options: [
        { id: 'a', text: 'United States' },
        { id: 'b', text: 'France' },
        { id: 'c', text: 'Germany' },
        { id: 'd', text: 'United Kingdom' },
      ],
      correctOptionId: 'd',
      category: 'history',
    },
    {
      id: 'q-his-8',
      text: 'The French Revolution began in which year?',
      options: [
        { id: 'a', text: '1776' },
        { id: 'b', text: '1789' },
        { id: 'c', text: '1799' },
        { id: 'd', text: '1812' },
      ],
      correctOptionId: 'b',
      category: 'history',
    },
    {
      id: 'q-his-9',
      text: 'Who was the British Prime Minister during most of World War II?',
      options: [
        { id: 'a', text: 'Neville Chamberlain' },
        { id: 'b', text: 'Winston Churchill' },
        { id: 'c', text: 'Clement Attlee' },
        { id: 'd', text: 'Margaret Thatcher' },
      ],
      correctOptionId: 'b',
      category: 'history',
    },
    {
      id: 'q-his-10',
      text: 'Which ancient wonder of the world still stands today?',
      options: [
        { id: 'a', text: 'Colossus of Rhodes' },
        { id: 'b', text: 'Hanging Gardens' },
        { id: 'c', text: 'Great Pyramid of Giza' },
        { id: 'd', text: 'Lighthouse of Alexandria' },
      ],
      correctOptionId: 'c',
      category: 'history',
    },
  ],
  geography: [
    {
      id: 'q-geo-1',
      text: 'What is the capital of Australia?',
      options: [
        { id: 'a', text: 'Sydney' },
        { id: 'b', text: 'Melbourne' },
        { id: 'c', text: 'Canberra' },
        { id: 'd', text: 'Brisbane' },
      ],
      correctOptionId: 'c',
      category: 'geography',
    },
    {
      id: 'q-geo-2',
      text: 'Which is the longest river in the world?',
      options: [
        { id: 'a', text: 'Amazon' },
        { id: 'b', text: 'Nile' },
        { id: 'c', text: 'Yangtze' },
        { id: 'd', text: 'Mississippi' },
      ],
      correctOptionId: 'b',
      category: 'geography',
    },
    {
      id: 'q-geo-3',
      text: 'What is the smallest continent by land area?',
      options: [
        { id: 'a', text: 'Europe' },
        { id: 'b', text: 'Australia' },
        { id: 'c', text: 'Antarctica' },
        { id: 'd', text: 'South America' },
      ],
      correctOptionId: 'b',
      category: 'geography',
    },
    {
      id: 'q-geo-4',
      text: 'Mount Everest is located in which mountain range?',
      options: [
        { id: 'a', text: 'Andes' },
        { id: 'b', text: 'Alps' },
        { id: 'c', text: 'Rockies' },
        { id: 'd', text: 'Himalayas' },
      ],
      correctOptionId: 'd',
      category: 'geography',
    },
    {
      id: 'q-geo-5',
      text: 'Which country has the most natural lakes?',
      options: [
        { id: 'a', text: 'United States' },
        { id: 'b', text: 'Russia' },
        { id: 'c', text: 'Canada' },
        { id: 'd', text: 'Brazil' },
      ],
      correctOptionId: 'c',
      category: 'geography',
    },
    {
      id: 'q-geo-6',
      text: 'What is the largest ocean on Earth?',
      options: [
        { id: 'a', text: 'Atlantic Ocean' },
        { id: 'b', text: 'Indian Ocean' },
        { id: 'c', text: 'Arctic Ocean' },
        { id: 'd', text: 'Pacific Ocean' },
      ],
      correctOptionId: 'd',
      category: 'geography',
    },
    {
      id: 'q-geo-7',
      text: 'Which African country has the largest population?',
      options: [
        { id: 'a', text: 'Egypt' },
        { id: 'b', text: 'South Africa' },
        { id: 'c', text: 'Nigeria' },
        { id: 'd', text: 'Ethiopia' },
      ],
      correctOptionId: 'c',
      category: 'geography',
    },
    {
      id: 'q-geo-8',
      text: 'What is the capital of Canada?',
      options: [
        { id: 'a', text: 'Toronto' },
        { id: 'b', text: 'Vancouver' },
        { id: 'c', text: 'Ottawa' },
        { id: 'd', text: 'Montreal' },
      ],
      correctOptionId: 'c',
      category: 'geography',
    },
    {
      id: 'q-geo-9',
      text: 'The Strait of Gibraltar connects which two bodies of water?',
      options: [
        { id: 'a', text: 'Red Sea and Mediterranean' },
        { id: 'b', text: 'Atlantic and Mediterranean' },
        { id: 'c', text: 'Pacific and Indian' },
        { id: 'd', text: 'Black Sea and Caspian Sea' },
      ],
      correctOptionId: 'b',
      category: 'geography',
    },
    {
      id: 'q-geo-10',
      text: 'Which US state is the Grand Canyon located in?',
      options: [
        { id: 'a', text: 'Nevada' },
        { id: 'b', text: 'Utah' },
        { id: 'c', text: 'Colorado' },
        { id: 'd', text: 'Arizona' },
      ],
      correctOptionId: 'd',
      category: 'geography',
    },
  ],
  sports: [
    {
      id: 'q-spo-1',
      text: 'In which sport would you perform a "slam dunk"?',
      options: [
        { id: 'a', text: 'Volleyball' },
        { id: 'b', text: 'Basketball' },
        { id: 'c', text: 'Tennis' },
        { id: 'd', text: 'Baseball' },
      ],
      correctOptionId: 'b',
      category: 'sports',
    },
    {
      id: 'q-spo-2',
      text: 'Which country hosted the first modern Olympic Games in 1896?',
      options: [
        { id: 'a', text: 'France' },
        { id: 'b', text: 'Italy' },
        { id: 'c', text: 'Greece' },
        { id: 'd', text: 'United Kingdom' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
    {
      id: 'q-spo-3',
      text: 'What is the maximum number of clubs a golfer can carry in their bag?',
      options: [
        { id: 'a', text: '12' },
        { id: 'b', text: '14' },
        { id: 'c', text: '16' },
        { id: 'd', text: '18' },
      ],
      correctOptionId: 'b',
      category: 'sports',
    },
    {
      id: 'q-spo-4',
      text: 'Which tennis player has won the most Grand Slam titles (men)?',
      options: [
        { id: 'a', text: 'Rafael Nadal' },
        { id: 'b', text: 'Novak Djokovic' },
        { id: 'c', text: 'Roger Federer' },
        { id: 'd', text: 'Pete Sampras' },
      ],
      correctOptionId: 'b',
      category: 'sports',
    },
    {
      id: 'q-spo-5',
      text: 'In soccer, what is the duration of a standard match?',
      options: [
        { id: 'a', text: '60 minutes' },
        { id: 'b', text: '80 minutes' },
        { id: 'c', text: '90 minutes' },
        { id: 'd', text: '100 minutes' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
    {
      id: 'q-spo-6',
      text: 'Which country has won the most FIFA World Cups?',
      options: [
        { id: 'a', text: 'Germany' },
        { id: 'b', text: 'Argentina' },
        { id: 'c', text: 'Brazil' },
        { id: 'd', text: 'Italy' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
    {
      id: 'q-spo-7',
      text: 'What is the term for a score of zero in tennis?',
      options: [
        { id: 'a', text: 'Nil' },
        { id: 'b', text: 'Zero' },
        { id: 'c', text: 'Love' },
        { id: 'd', text: 'Blank' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
    {
      id: 'q-spo-8',
      text: 'In which sport is the term "home run" used?',
      options: [
        { id: 'a', text: 'Cricket' },
        { id: 'b', text: 'Baseball' },
        { id: 'c', text: 'Softball' },
        { id: 'd', text: 'Golf' },
      ],
      correctOptionId: 'b',
      category: 'sports',
    },
    {
      id: 'q-spo-9',
      text: 'How many players are on a standard soccer team on the field?',
      options: [
        { id: 'a', text: '9' },
        { id: 'b', text: '10' },
        { id: 'c', text: '11' },
        { id: 'd', text: '12' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
    {
      id: 'q-spo-10',
      text: 'What is the national sport of Japan?',
      options: [
        { id: 'a', text: 'Karate' },
        { id: 'b', text: 'Judo' },
        { id: 'c', text: 'Sumo' },
        { id: 'd', text: 'Kendo' },
      ],
      correctOptionId: 'c',
      category: 'sports',
    },
  ],
  entertainment: [
    {
      id: 'q-ent-1',
      text: 'Who directed the movie "Jurassic Park"?',
      options: [
        { id: 'a', text: 'James Cameron' },
        { id: 'b', text: 'Steven Spielberg' },
        { id: 'c', text: 'George Lucas' },
        { id: 'd', text: 'Ridley Scott' },
      ],
      correctOptionId: 'b',
      category: 'entertainment',
    },
    {
      id: 'q-ent-2',
      text: 'What is the name of the wizarding school in Harry Potter?',
      options: [
        { id: 'a', text: 'Durmstrang' },
        { id: 'b', text: 'Beauxbatons' },
        { id: 'c', text: 'Hogwarts' },
        { id: 'd', text: 'Ilvermorny' },
      ],
      correctOptionId: 'c',
      category: 'entertainment',
    },
    {
      id: 'q-ent-3',
      text: 'Which band released the album "Abbey Road"?',
      options: [
        { id: 'a', text: 'The Rolling Stones' },
        { id: 'b', text: 'The Beatles' },
        { id: 'c', text: 'The Who' },
        { id: 'd', text: 'Led Zeppelin' },
      ],
      correctOptionId: 'b',
      category: 'entertainment',
    },
    {
      id: 'q-ent-4',
      text: 'What year was the first Marvel Cinematic Universe movie released?',
      options: [
        { id: 'a', text: '2005' },
        { id: 'b', text: '2008' },
        { id: 'c', text: '2010' },
        { id: 'd', text: '2012' },
      ],
      correctOptionId: 'b',
      category: 'entertainment',
    },
    {
      id: 'q-ent-5',
      text: 'Who played Jack in the movie "Titanic"?',
      options: [
        { id: 'a', text: 'Brad Pitt' },
        { id: 'b', text: 'Tom Cruise' },
        { id: 'c', text: 'Leonardo DiCaprio' },
        { id: 'd', text: 'Johnny Depp' },
      ],
      correctOptionId: 'c',
      category: 'entertainment',
    },
    {
      id: 'q-ent-6',
      text: 'What is the highest-grossing film of all time (unadjusted)?',
      options: [
        { id: 'a', text: 'Avengers: Endgame' },
        { id: 'b', text: 'Avatar' },
        { id: 'c', text: 'Titanic' },
        { id: 'd', text: 'Star Wars: The Force Awakens' },
      ],
      correctOptionId: 'b',
      category: 'entertainment',
    },
    {
      id: 'q-ent-7',
      text: 'Which streaming service features "Stranger Things"?',
      options: [
        { id: 'a', text: 'Hulu' },
        { id: 'b', text: 'Amazon Prime' },
        { id: 'c', text: 'Netflix' },
        { id: 'd', text: 'Disney+' },
      ],
      correctOptionId: 'c',
      category: 'entertainment',
    },
    {
      id: 'q-ent-8',
      text: 'Who wrote the "Game of Thrones" books?',
      options: [
        { id: 'a', text: 'J.R.R. Tolkien' },
        { id: 'b', text: 'George R.R. Martin' },
        { id: 'c', text: 'Stephen King' },
        { id: 'd', text: 'Brandon Sanderson' },
      ],
      correctOptionId: 'b',
      category: 'entertainment',
    },
    {
      id: 'q-ent-9',
      text: "What is the name of Batman's butler?",
      options: [
        { id: 'a', text: 'James' },
        { id: 'b', text: 'Peter' },
        { id: 'c', text: 'Alfred' },
        { id: 'd', text: 'Thomas' },
      ],
      correctOptionId: 'c',
      category: 'entertainment',
    },
    {
      id: 'q-ent-10',
      text: 'Which animated film features a character named Simba?',
      options: [
        { id: 'a', text: 'Bambi' },
        { id: 'b', text: 'The Jungle Book' },
        { id: 'c', text: 'The Lion King' },
        { id: 'd', text: 'Tarzan' },
      ],
      correctOptionId: 'c',
      category: 'entertainment',
    },
  ],
};

export async function fetchQuestions(
  settings: RoomSettings
): Promise<Question[]> {
  const { questionCount, category } = settings;

  const questions = QUESTION_BANK[category] || QUESTION_BANK.general;

  // Shuffle and slice to get requested count
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, questionCount);
}
