import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Bricolage_Grotesque, Geist } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/layout/theme-provider';
import { cn } from '@/lib/utils';

// Body / UI — loaded with swap so layout doesn't block on the font.
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// Headings — same reasoning. Monospace slot is served by the system stack
// (see `--font-mono` in globals.css) — the only mono usage is 6-char room
// codes, which does not justify a Google Fonts round trip.
const bricolageGrotesque = Bricolage_Grotesque({
  variable: '--font-heading',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        bricolageGrotesque.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <Suspense>
          <ThemeProvider
            attribute="class"
            defaultTheme="white"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
